### ISSUE TITLE
TokenSale - constant functions

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#12]
**LOW IMPORTANCE** - Functions which are not modifying Blockchain state should have **constant** modifier like `getTokenAddress`.

**Comment by agarwalakarsh** [comment]
We will not be needing `getTokenAddress`, `getStartTimestamp`, `getEndTimestamp` and `getICOState` functions. Hence, removing them from the code. Thus solving the problem.
