### ISSUE TITLE
TokenSale - pre sale tokens added to ICO tokens

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#13]
**LOW IMPORTANCE** - Does `icoTokenRaised` denotes all tokens distributed during Presale and ICO? If not, in `isPreSalePeriod` function, this should be removed - `icoTokenRaised = presaleTokenRaised`.

**Comment by agarwalakarsh** [comment]
Yes, icoTokenRaised represents all the tokens raised during the ICO. Hence the statement.

**Comment by rohendra** [comment]
`icoTokenRaised` here ICO refers to presale as well as ICO tokens. But `TOKEN_PER_ETH_ICOSALE' in this case ICO refers to ICO only and not presale. 
Naming should be consistent. It is confusing. For example `icoTokenRaised' tokens are not raised, ether will be raised, tokens will be distributed.

**Comment by agarwalakarsh** [comment]
I've duly noted your response and have made the edits in the code. In the meantime, I did find a CRITICAL error in the Ending conditions for the Crowd Sale and have resolved it. Here is the commit link:

https://github.com/MLG-Blockchain/HIREToken/commit/e0f7e11f0d8fd2960aa7f501e8a54361c499fd5d
