### ISSUE TITLE
TokenSale - Not a constant function

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#14]
**LOW IMPORTANCE** - Function `isPreSalePeriod` is marked as **constant** even though it is modifying variables.

**Comment by agarwalakarsh** [comment]
Constant is defined for the returned value. Even a state changing function can keep constant as its modifier. It just notifies about the return value, which has to be uneditable.

**Comment by agarwalakarsh** [comment]
Removed the `constant` from the `isPreSalePeriod` and `isICOPeriod` functions.

**Comment by rohendra** [comment]
> Constant is defined for the returned value. Even a state changing function can keep constant as its modifier. It just notifies about the return value, which has to be uneditable.
constant modifier in function is not used to denote that the returned value is a constant.

**Comment by agarwalakarsh** [comment]
I was in a notion of otherwise. Thanks for the heads up. I've already made the necessary changes.
