### ISSUE TITLE
TokenSale - buyTokens function is broken

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#19]
**CRITICAL** - In `buyTokens` function, this statement `token.transfer(_recipient, _value)` will not work after `transfer(...)` function is fixed as mentioned in **BasicToken Contract** section.

**Comment by agarwalakarsh** [comment]
Can you please elaborate? I didn't quite get the context.

**Comment by agarwalakarsh** [comment]
Corrected the errors and the bugs. Here is the commit link:

https://github.com/MLG-Blockchain/HIREToken/commit/637d8fd2b78ef838fa0b7a409afaeac0b9199da1
