### ISSUE TITLE
CRITICAL - In transfer(...) function, there should be a check that transaction sender has minimum _value balance and _value is not zero.

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#2]

**Comment by agarwalakarsh** [comment]
I have put this check in the TokenSale.sol contract as a modifier, "nonZero". This will allow us to check the amount transferred. Also, it is the payable function so it will only go through if the person has that much amount of ether.

I have incorporated the check for _value > 0.
