### ISSUE TITLE
TokenSale - Inconsistent state changes

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#20]
**CRITICAL IMPORTANCE** - Once ICO starts, there is no way its state will change from *PreSale* to something else. This is because `isCrowdSaleStatePreSale` and `isCrowdSaleStateICO` are not checking if state has changed or they should be avoided and only `isPreSalePeriod` and `isICOPeriod` should be used. It is Recommended that all state changes are thoroughly checked.

**Comment by agarwalakarsh** [comment]
Every time anyone buys tokens, we check for a number of remaining tokens left and can the person buy that much amount of tokens or not. The state will be checked and changed every time anyone buys a token.

I made a silly mistake of not considering a common test case. Here is the commit link:
https://github.com/MLG-Blockchain/HIREToken/commit/ab91d38b5cc6debed6c91af243be6802ad71e3c4
