### ISSUE TITLE
issue #4 not fixed. Creating new issue as I can't reopen

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#21]
function is misspelled and is not checking allowance etc. It is being overriden in StandardToken, better keep it empty or remove it.

**Comment by agarwalakarsh** [comment]
Duly noted and removed the code from the BasicToken.sol. Here is the commit link:

https://github.com/MLG-Blockchain/HIREToken/commit/637d8fd2b78ef838fa0b7a409afaeac0b9199da1
