### ISSUE TITLE
BasicToken - CRITICAL - In transfer(...) function, amount is not being deducted from sender's balance! This allows any one to transfer any amount without ever reducing their own balance.

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#3]

**Comment by agarwalakarsh** [comment]
The sender is the TokenSale.sol contract here.
The buyer calls the functions from the TokenSale.sol where we have used payable in "buyTokens" function so we have the balance deducted from the sender.

Next, we call the tranfer function in Token.sol, where we just edit the amount invested. So, I don't really think we are losing any tokens without any money.

**Comment by rohendra** [comment]
`transfer` function is meant to be used by anyone. fix is needed for this, include commit link in your comment.

**Comment by agarwalakarsh** [comment]
Yes, I have duly noted and already corrected it in my last commit. Here is the commit link:

https://github.com/MLG-Blockchain/HIREToken/commit/637d8fd2b78ef838fa0b7a409afaeac0b9199da1
