### ISSUE TITLE
BasicToken - LOW IMPORTANCE - In tranferFrom(...) function is not being used and should be removed.

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#4]

**Comment by agarwalakarsh** [comment]
The function to facilitate the token transfer after the ICO has ended. The tokens are shouldn't be burnt and thus should allow transfer from one owner to another.

**Comment by rohendra** [comment]
`tranferFrom` is misspelled then. change name to match `function transferFrom(address _from, address _to, uint _value) returns (bool success)` this.
