### ISSUE TITLE
StandardToken - potential re-entrancy attack

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#7]
**HIGH IMPORTANCE** - In `transferFrom` function 
      `balances[_from] = balances[_from].sub(_value);` <br/>
      `balances[_to] = balances[_to].add(_value);` <br/>
      `allowed[_from][msg.sender] = _allowance.sub(_value);` <br/> <br/>

Allowance subtraction should be made before addition to prevent a **re-entrancy attack**. We recommend re-ordering these lines.

**Comment by agarwalakarsh** [comment]
Duly noted and edited.
