### ISSUE TITLE
StandardToken - ERC20 compliance

### ISSUE THREAD

**Issue by rohendra** [MLG-Blockchain/HIREToken#9]
**LOW IMPORTANCE** - `approve` function name and signature should strictly match with `function approve(address _spender, uint _value) returns (bool success)` else token will not be ERC20 compliant.

**LOW IMPORTANCE** - `allowance` function name and signature should strictly match with `function allowance(address _owner, address _spender) constant returns (uint remaining)` else token will not be ERC20 compliant.

**Comment by agarwalakarsh** [comment]
Duly noted and edited.
